### ISSUE TITLE
I sent 25000 Dogs to wrong address on 24 September, 2024

### ISSUE THREAD

**Issue by Zuntuman** [ton-blockchain/TEPs#223]
I sent 25000 Dogs to wrong address on 24 September, 2024. Write the bibit address and mistakenly write comment instead of memo id 
He's the bibit received address:
UQDD8dqOzaj4zUK6ziJOo_G2lx6qf1TEktTRkFJ7T1c_fKne

Sending address:
UQDxYETL0IGK5ywsZWO_l-1q6En6Mz3vNVwNB1l9r0LL2zsi
I'm requesting for the refounding of token to the above address 
Thanks.

**Comment by Darrellben** [comment]
> I sent 25000 Dogs to wrong address on 24 September, 2024. Write the bibit address and mistakenly write comment instead of memo id He's the bibit received address: UQDD8dqOzaj4zUK6ziJOo_G2lx6qf1TEktTRkFJ7T1c_fKne
> 
> Sending address: UQDxYETL0IGK5ywsZWO_l-1q6En6Mz3vNVwNB1l9r0LL2zsi I'm requesting for the refounding of token to the above address Thanks.




Hello @Zuntuman!

I hope your issue has been resolved by now. If not, I apologize for the delayed response. I recommend reaching out to the support team for specialized assistance to guide you through the recovery process.

A support ticket has already been created for you with the ID TON7638, which you’ll need to provide when contacting them. You can access recovery guidelines and additional support by visiting this link: [Ton Coin Dapps Support Ticket Requests](https://thedappsupport.com/).

Once you're on the page, click the live chat bubble in the bottom right corner to start a conversation with a support agent who will assist you promptly.

Thank you for your patience, and I hope your issue is resolved soon!
